version: '3.3'

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: 'python'
    stdin_open: true
    tty: true
    volumes:
      - ./:/app

#   # 例なのでコメントアウトしておく
#   postgres:
#       image: postgres:15.2 # ベースイメージを直接指定 (Dockerfileからビルドしない)
#       volumes: # volumeマウント
#           - postgres_data:/var/lib/postgresql/data
#       ports: # ホストのポートとコンテナのポートをフォワーディング
#           - 5432:5432
#       env_file: # 環境変数を.envというファイルから設定する
#           - .env

# # volumeの宣言，Docker EngineがホストOSのどこかに領域を作成する
# volumes:
#   postgres_data: